"""Standard UPPER_SNAKE codes (STANDARDS.md §7). Add new codes here, never inline."""

from __future__ import annotations

# cause_code
ORDER_CANCELED_AFTER_PAYMENT = "ORDER_CANCELED_AFTER_PAYMENT"
ORDER_UNAVAILABLE_AFTER_PAYMENT = "ORDER_UNAVAILABLE_AFTER_PAYMENT"
SELLER_LATE_HANDOVER = "SELLER_LATE_HANDOVER"
CARRIER_LATE_DELIVERY = "CARRIER_LATE_DELIVERY"
SPLIT_PAYMENT_VALID = "SPLIT_PAYMENT_VALID"
PAYMENT_AMOUNT_MISMATCH = "PAYMENT_AMOUNT_MISMATCH"
DUPLICATE_PAYMENT_CAPTURED = "DUPLICATE_PAYMENT_CAPTURED"
REFUND_NOT_COMPLETED = "REFUND_NOT_COMPLETED"
REFUND_PROCESSING_FAILED = "REFUND_PROCESSING_FAILED"
CLAIM_NOT_SUPPORTED_BY_EVIDENCE = "CLAIM_NOT_SUPPORTED_BY_EVIDENCE"
EVIDENCE_UNAVAILABLE = "EVIDENCE_UNAVAILABLE"

# resolution_actions (standard EC_POLICY_V1 policy actions)
ACTION_ISSUE_REFUND = "issue_refund"
ACTION_REFUND_FREIGHT = "refund_freight"
ACTION_MONITOR_REFUND = "monitor_refund"
ACTION_RETRY_REFUND = "retry_refund"
ACTION_DOCUMENT_NO_ACTION = "document_no_action"
ACTION_REQUEST_MANUAL_REVIEW = "request_manual_review"

# Legacy uppercase action aliases kept for backward compatibility
REFUND_FULL = ACTION_ISSUE_REFUND
REFUND_PARTIAL = ACTION_ISSUE_REFUND
REFUND_DUPLICATE_CHARGE = ACTION_ISSUE_REFUND
RETRY_REFUND = ACTION_RETRY_REFUND
MONITOR_REFUND = ACTION_MONITOR_REFUND
ESCALATE_TO_SELLER = ACTION_REFUND_FREIGHT
ESCALATE_TO_LOGISTICS = ACTION_REFUND_FREIGHT
EXPLAIN_SPLIT_PAYMENT = ACTION_DOCUMENT_NO_ACTION
REJECT_CLAIM = ACTION_DOCUMENT_NO_ACTION
REQUEST_MANUAL_REVIEW = ACTION_REQUEST_MANUAL_REVIEW

# refund reason_code
CANCELED_ORDER_REFUND = "CANCELED_ORDER_REFUND"
UNAVAILABLE_ORDER_REFUND = "UNAVAILABLE_ORDER_REFUND"
PAYMENT_DIFFERENCE_REFUND = "PAYMENT_DIFFERENCE_REFUND"
DUPLICATE_CHARGE_REFUND = "DUPLICATE_CHARGE_REFUND"
FAILED_REFUND_REISSUE = "FAILED_REFUND_REISSUE"
PENDING_REFUND_MONITORING = "PENDING_REFUND_MONITORING"
LATE_DELIVERY_COMPENSATION = "LATE_DELIVERY_COMPENSATION"

# data_conflicts.resolution_code
PREFER_MCP_SOURCE = "PREFER_MCP_SOURCE"
PREFER_LATEST_RECORD = "PREFER_LATEST_RECORD"
UNRESOLVED = "UNRESOLVED"

# policy_decided.decision_code
POLICY_REFUND_ELIGIBLE = "POLICY_REFUND_ELIGIBLE"
POLICY_REFUND_NOT_ELIGIBLE = "POLICY_REFUND_NOT_ELIGIBLE"
POLICY_NEEDS_REVIEW = "POLICY_NEEDS_REVIEW"

# verification_completed.decision_code
PASS = "PASS"
REPAIRED = "REPAIRED"
DOWNGRADED = "DOWNGRADED"

# specialist findings["claim_check"][topic] values (read by coordinator for unsupported_claim)
CLAIM_SUPPORTED = "CLAIM_SUPPORTED"
CLAIM_CONTRADICTED = "CLAIM_CONTRADICTED"
